2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/.config/wandb/settings
2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/settings
2022-02-21 21:53:40,252 WARNING MainThread:12041 [wandb_setup.py:_flush():75] Unknown environment variable: WANDB_CONFIG_DIR
2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_init.py:_log_setup():386] Logging user logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220221_215340-2h38lppu/logs/debug.log
2022-02-21 21:53:40,252 INFO    MainThread:12041 [wandb_init.py:_log_setup():387] Logging internal logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220221_215340-2h38lppu/logs/debug-internal.log
2022-02-21 21:53:40,253 INFO    MainThread:12041 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x17656ab50>
2022-02-21 21:53:40,254 INFO    MainThread:12041 [wandb_init.py:init():420] calling init triggers
2022-02-21 21:53:40,254 INFO    MainThread:12041 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'Architecture': 'Basic UNet', 'epochs': 1, 'batch_size': 1, 'learning_rate': 0.0001, 'dropout': 0.5}
2022-02-21 21:53:40,254 INFO    MainThread:12041 [wandb_init.py:init():471] starting backend
2022-02-21 21:53:40,254 INFO    MainThread:12041 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-21 21:53:40,266 INFO    MainThread:12041 [backend.py:ensure_launched():219] starting backend process...
2022-02-21 21:53:40,273 INFO    MainThread:12041 [backend.py:ensure_launched():224] started backend process with pid: 12051
2022-02-21 21:53:40,276 INFO    MainThread:12041 [wandb_init.py:init():480] backend started and connected
2022-02-21 21:53:40,292 INFO    MainThread:12041 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-21 21:53:40,294 INFO    MainThread:12041 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-21 21:53:40,294 INFO    MainThread:12041 [wandb_init.py:init():550] updated telemetry
2022-02-21 21:53:40,296 INFO    MainThread:12041 [wandb_init.py:init():581] communicating current version
2022-02-21 21:53:40,948 INFO    MainThread:12041 [wandb_init.py:init():586] got version response 
2022-02-21 21:53:40,948 INFO    MainThread:12041 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-21 21:53:41,287 INFO    MainThread:12041 [wandb_init.py:init():624] starting run threads in backend
2022-02-21 21:53:44,661 INFO    MainThread:12041 [wandb_run.py:_console_start():1827] atexit reg
2022-02-21 21:53:44,661 INFO    MainThread:12041 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-21 21:53:44,661 INFO    MainThread:12041 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-21 21:53:44,662 INFO    MainThread:12041 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-21 21:53:44,662 INFO    MainThread:12041 [wandb_init.py:init():651] run started, returning control to user process
2022-02-21 21:53:44,672 INFO    MainThread:12041 [wandb_watch.py:watch():43] Watching
2022-02-21 21:53:47,040 INFO    MainThread:12041 [wandb_run.py:finish():1468] finishing run wwy/Basic UNet (dropout-0.5 & lr-0.0001 & epochs-1)/2h38lppu
2022-02-21 21:53:47,040 INFO    MainThread:12041 [jupyter.py:save_history():429] not saving jupyter history
2022-02-21 21:53:47,040 INFO    MainThread:12041 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-21 21:53:47,040 INFO    MainThread:12041 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-21 21:53:47,040 INFO    MainThread:12041 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-21 21:53:47,041 INFO    MainThread:12041 [wandb_run.py:_restore():1769] restore
2022-02-21 21:53:47,707 INFO    MainThread:12041 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 640
  total_bytes: 640
}

